# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed76611b899f3486d47d7bd87935b7bca0eefd49e3c4886b48d1d6a572e5fc92cb83e0e656eb5d98aa06c7b4f2edc7842a36fd4c3043892f90e13a4e5450b758

test:
  secret_key_base: 09f0c0b1661a68a31eab0ff6268ef33038e9107839d3da01964fe9f6f1966921c7ec50ed6c453b406153e54c860ac7cea1b39a65570ed65da1b132db6eb13427

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
